// curses_data.c
#include "curses_data.h" 

/* curses data */
const char *curses[] = {
	"aardvark",
	"abecedarians",
	"addle-pated lumps of anthracite",
	"anachronisms",
	"anacoluthons",
	"antediluvian bulldozer",
	"anthracite",
	"anthropithecus",
	"anthropophagus",
	"artichokes",
	"baboons",
	"bagpipers",
	"bald-headed budgerigar",
	"bashi-bazouks",
	"bath-tub admiral",
	"belemnite",
	"black marketers",
	"blackamoor",
	"blistering barnacles",
	"blistereing blundering bird-brain ",
	"blunderbuss",
	"bootlegger",
	"borgia",
	"bougainvillea",
	"breathalyser",
	"cachinnating cockatoo",
	"carpathian bashi-bazouks ",
	"carpetsellers",
	"caterpillars",
	"centipede",
	"cercopithecus",
	"certified diplodocuses ",
	"coconut",
	"coelcanth",
	"colocynths",
	"corsair",
	"cowards",
	"crabapples",
	"cro-magnon",
	"crooks",
	"cushion footed quadrupeds",
	"cyclotron",
	"diplodocus",
	"dizzards ",
	"dogs",
	"doryphore",
	"doryphores",
	"duck-billed platypus",
	"dunderheaded coconuts",
	"dynamiter",
	"fancy-dress freebooter ",
	"fatfaces",
	"filibuster",
	"fourlegged cyrano",
	"freshwater pirate ",
	"freshwater swabs",
	"fuzzy wuzzy",
	"gallows-fodder",
	"gangof theives",
	"gibbering anthropoids",
	"gobbledgook",
	"goosecaps",
	"guano-gatherers ",
	"harlequin",
	"iconoclasts",
	"... you, imitation incas, you ",
	"you, interplantary goat, you ",
	"jobbernowl ",
	"koua kouakouin kouinkouin koua kouin koua ",
	"lily-livered landlubbers",
	"lubberscum",
	"macrocephalic baboon",
	"megacycle pyromaniac",
	"miserable blundering barbecued blister",
	"miserable earth worms",
	"miserable miser",
	"miserable molecule of mildew",
	"moujiks",
	"nanny goat",
	"nincompoop",
	"nitwitted ninepins",
	"nyctalops",
	"odd-toed ungulate",
	"ophicleides",
	"ostrogoth",
	"pachyrhizus",
	"pestilential pachyderm",
	"phylloxera",
	"pithecanthropic montebanks",
	"pithecanthropic pickpocket ",
	"pithecanthropus ",
	"poltroons",
	"polygraphs",
	"puffed-up punchinello ",
	"purple profiteering jellyfish",
	"pyromaniac",
	"raggle taggle ruminants",
	"rapscallion",
	"rhizopods",
	"rkrpxzkrmtfrz",
	"sea-gherkin",
	"sea-lice",
	"shipwreckers",
	"slubberdegullions",
	"steamroller",
	"stoolpigeon",
	"subtropical sea-louse",
	"terrapins",
	"terrorists",
	"thundering typhoons",
	"tin hatted tyrants",
	"toffee-noses",
	"troglodytes",
	"turncoats",
	"two-timing tartar twisters ",
	"two-timing troglodytes",
	"vegetarian",
	"vermicellis",
	"viper",
	"visigoths",
	"weevils",
	"whippersnapper",
	"woodlice",
	"young monkey ",
	"zapotecs"
};

/* Size of the array */
const int NUM_CURSES = sizeof(curses) / sizeof(curses[0]);
